vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.signcolumn = 'yes'
vim.opt.termguicolors = true
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.cmdheight = 0
vim.opt.cursorline = true
vim.opt.copyindent = true
vim.opt.undofile = true
vim.opt.wrap = false
vim.opt.writebackup = false
vim.opt.breakindent = true
vim.opt.mouse = 'a'
vim.opt.relativenumber = true
vim.opt.clipboard = 'unnamedplus'
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.completeopt = 'menuone,noselect'
vim.opt.scrolloff = 8
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
